# Generated by Django 6.0.5 on 2026-06-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_label_note_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
