# Generated by Django 6.0.5 on 2026-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
