# Generated by Django 6.0.5 on 2026-07-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_noteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
