# Generated by Django 6.0.5 on 2026-07-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_noteimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='noteimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='note',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
