# Generated by Django 6.0.5 on 2026-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_note_options_alter_noteimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='total_view_seconds',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
