# Generated by Django 6.0.5 on 2026-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_label_unique_label_name_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
