# Generated by Django 6.0.5 on 2026-09-10 05:59

from django.db import migrations



# 既存ノートのorderに順番を付ける。
def set_initial_order(apps, schema_editor):

    Note = apps.get_model("notes", "Note")

    user_ids = (
        Note.objects
        .values_list("user_id", flat=True)
        .distinct()
    )

    for user_id in user_ids:
        notes = (
            Note.objects
            .filter(user_id=user_id)
            .order_by("-created_at", "-id")
        )

        for index, note in enumerate(notes):
            note.order = index
            note.save(update_fields=["order"])




class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0015_note_order"),
    ]

    operations = [
        migrations.RunPython(
            set_initial_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]


# class Migration(migrations.Migration):

#     dependencies = [
#         ('notes', '0015_note_order'),
#     ]

#     operations = [
#     ]
