# Generated by Django 6.0.5 on 2026-09-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20260910_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='note',
            name='pinned_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
