# Generated by Django 6.0.5 on 2026-09-11 03:28

from django.db import migrations



def set_initial_pinned_order(apps, schema_editor):

    Note = apps.get_model("notes", "Note")

    user_ids = (
        Note.objects
        .filter(is_pinned=True)
        .values_list("user_id", flat=True)
        .distinct()
    )


    for user_id in user_ids:
        notes = (
            Note.objects
            .filter(
                user_id=user_id,
                is_pinned=True,
            )
            .order_by("-created_at", "-id")
        )

        for index, note in enumerate(notes):
            note.pinned_order = index
            note.save(
                update_fields=["pinned_order"]
            )



class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0017_alter_note_options_note_pinned_order"),
    ]

    operations = [
        migrations.RunPython(set_initial_pinned_order),
    ]



# class Migration(migrations.Migration):

#     dependencies = [
#         ('notes', '0017_alter_note_options_note_pinned_order'),
#     ]

#     operations = [
#     ]
